[programs.localnet]
cross_pile = "6urrPCjcrQ1xaxbAJGMTtvZfA9wbMqQbEArKnVUHhYTs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = <Your Key Path Here>

[scripts]
test = "yarn run ts-mocha -p --parallel ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "mainnet"
[[test.validator.clone]]
address = "8nzxsNf74ZHDguHi51SjQWxDxegL2DBgxeGHA2pQVtTJ"
[[test.validator.clone]]
address = "K2z1qkxZdsw6WpFd63hqhqx9MYUc5c85NdbXULNeGhW"

